export const subjectsWithSubtopics = {
    "Natural Science": ["Natural Science","Biology","Chemistry","Geology"],
    "Art": ["Art", "Theater", "Sculpture", "Photography"],
    "History": ["History", "Archaeology", "Timeline", "Cultural Heritage"],
    "Psychology": ["Psychology", "Mental Health", "Behavior", "Therapy"],
    "Philosophy": ["Philosophy", "Ethics", "Logic", "Metaphysics"],
    "Mathematics": ["Mathematics", "Geometry", "Calculus", "Statistics"],
    "Architecture": ["Architecture", "Urbanism", "Building Design", "Sustainability"],
    "Music": ["Music", "Harmony", "Composition", "Performance"],
    "Politics": ["Politics", "Democracy", "Power Distribution", "Political System"],
    "Culture": ["Culture", "Traditions", "Artistic Expression", "Identity"],
    "Health Science": ["Health Science", "Epidemiology", "Medical Research", "Healthcare"],
    "Law": ["Law", "Legal System", "Legislation", "Legal Responsibility"],
    "Economics": [ "Economics", "Market Dynamics", "Capitalism", "Microeconomics"],
    "Information Technology": ["Information Technology", "Network Security", "Data Analysis", "Software Development"],
    "Programming": ["Programming", "Algorithms", "Web Development", "Object-Oriented Programming"],
    "Environmental Science": ["Environmental Science", "Climate Change", "Principles of Sustainability", "Ecological Balance"],
    "Education": ["Education", "Learning Theory", "Pedagogy", "School Leadership"],
    "Journalism": ["Journalism", "Press Ethics", "News Reporting", "Editorial Process"],
    "Communication": ["Communication", "Interpersonal Communication", "Mass Communication", "Digital Communication"],
    "Religion": ["Religion", "Theology", "Religious Practice", "Spiritual Development"],
    "Sociology": ["Sociology", "Social Structures", "Social Movements", "Cultural Diversity"],
    "Agricultural Science": ["Agricultural Science", "Agronomy", "Animal Husbandry", "Sustainable Agricultural Practices"]
};
